# Generated by Django 4.2.2 on 2023-06-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copperknight", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="nothing.png", upload_to="images/"),
        ),
    ]
