# Generated by Django 4.2.2 on 2023-06-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copperknight", "0002_user_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
    ]
