# Generated by Django 4.2.2 on 2023-06-27 02:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copperknight", "0003_opus_remove_user_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Opus",
        ),
    ]
