# Generated by Django 4.2.2 on 2023-06-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copperknight", "0005_opus"),
    ]

    operations = [
        migrations.AddField(
            model_name="opus",
            name="title",
            field=models.CharField(default="Unnamed Opus", max_length=100),
        ),
    ]
