# Generated by Django 4.2.2 on 2023-06-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copperknight", "0006_opus_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="opus",
            name="img_private",
            field=models.BooleanField(default=False),
        ),
    ]
