# Generated by Django 4.2.2 on 2023-06-28 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("copperknight", "0007_opus_img_private"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoritedOpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="copperknight.opus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
